<?php

return [
	'jqadm' => [
        'swpost' => [
            'standard' => [
                'subparts' => [
                    'media' => 'media',
                    'text' => 'text',
                ],
            ],
            'domains' => [
                'media' => 'media',
                'text' => 'text',
            ],
            'icons' => [
                    'adobe'=>'Adobe',
                    'airbnb'=>'Airbnb',
                    'algolia'=>'Algolia',
                    'amazon'=>'Amazon',
                    'android'=>'Android',
                    'angular'=>'Angular',
                    'apple'=>'Apple',
                    'audible'=>'Audible',
                    'baidu'=>'Baidu',
                    'behance'=>'Behance',
                    'bing'=>'Bing',
                    'bitcoin'=>'Bitcoin',
                    'blender'=>'Blender',
                    'blogger'=>'Blogger',
                    'bootstrap'=>'Bootstrap',
                    'chrome'=>'Chrome',
                    'codepen'=>'Codepen',
                    'c-plus-plus'=>'C-plus-plus',
                    'creative-commons'=>'Creative-commons',
                    'css3'=>'Css3',
                    'dailymotion'=>'Dailymotion',
                    'deviantart'=>'Deviantart',
                    'dev-to'=>'Dev-to',
                    'digg'=>'Digg',
                    'digitalocean'=>'Digitalocean',
                    'discord'=>'Discord',
                    'discourse'=>'Discourse',
                    'django'=>'Django',
                    'dribbble'=>'Dribbble',
                    'dropbox'=>'Dropbox',
                    'drupal'=>'Drupal',
                    'ebay'=>'Ebay',
                    'edge'=>'Edge',
                    'etsy'=>'Etsy',
                    'facebook'=>'Facebook',
                    'facebook-circle'=>'Facebook-circle',
                    'facebook-square'=>'Facebook-square',
                    'figma'=>'Figma',
                    'firebase'=>'Firebase',
                    'firefox'=>'Firefox',
                    'flickr'=>'Flickr',
                    'flickr-square'=>'Flickr-square',
                    'foursquare'=>'Foursquare',
                    'git'=>'Git',
                    'github'=>'Github',
                    'gitlab'=>'Gitlab',
                    'google'=>'Google',
                    'google-cloud'=>'Google-cloud',
                    'google-plus'=>'Google-plus',
                    'google-plus-circle'=>'Google-plus-circle',
                    'html5'=>'Html5',
                    'imdb'=>'Imdb',
                    'instagram'=>'Instagram',
                    'instagram-alt'=>'Instagram-alt',
                    'internet-explorer'=>'Internet-explorer',
                    'invision'=>'Invision',
                    'javascript'=>'Javascript',
                    'joomla'=>'Joomla',
                    'jquery'=>'Jquery',
                    'jsfiddle'=>'Jsfiddle',
                    'kickstarter'=>'Kickstarter',
                    'kubernetes'=>'Kubernetes',
                    'less'=>'Less',
                    'linkedin'=>'Linkedin',
                    'linkedin-square'=>'Linkedin-square',
                    'magento'=>'Magento',
                    'mailchimp'=>'Mailchimp',
                    'markdown'=>'Markdown',
                    'mastercard'=>'Mastercard',
                    'medium'=>'Medium',
                    'medium-old'=>'Medium-old',
                    'medium-square'=>'Medium-square',
                    'messenger'=>'Messenger',
                    'microsoft'=>'Microsoft',
                    'microsoft-teams'=>'Microsoft-teams',
                    'nodejs'=>'Nodejs',
                    'ok-ru'=>'Ok-ru',
                    'opera'=>'Opera',
                    'patreon'=>'Patreon',
                    'paypal'=>'Paypal',
                    'periscope'=>'Periscope',
                    'pinterest'=>'Pinterest',
                    'pinterest-alt'=>'Pinterest-alt',
                    'play-store'=>'Play-store',
                    'pocket'=>'Pocket',
                    'product-hunt'=>'Product-hunt',
                    'python'=>'Python',
                    'quora'=>'Quora',
                    'react'=>'React',
                    'redbubble'=>'Redbubble',
                    'reddit'=>'Reddit',
                    'redux'=>'Redux',
                    'sass'=>'Sass',
                    'shopify'=>'Shopify',
                    'skype'=>'Skype',
                    'slack'=>'Slack',
                    'slack-old'=>'Slack-old',
                    'snapchat'=>'Snapchat',
                    'soundcloud'=>'Soundcloud',
                    'spotify'=>'Spotify',
                    'spring-boot'=>'Spring-boot',
                    'squarespace'=>'Squarespace',
                    'stack-overflow'=>'Stack-overflow',
                    'stripe'=>'Stripe',
                    'telegram'=>'Telegram',
                    'trello'=>'Trello',
                    'tumblr'=>'Tumblr',
                    'tux'=>'Tux',
                    'twitch'=>'Twitch',
                    'twitter'=>'Twitter',
                    'unsplash'=>'Unsplash',
                    'vimeo'=>'Vimeo',
                    'visa'=>'Visa',
                    'vk'=>'Vk',
                    'vuejs'=>'Vuejs',
                    'whatsapp'=>'Whatsapp',
                    'whatsapp-square'=>'Whatsapp-square',
                    'wikipedia'=>'Wikipedia',
                    'windows'=>'Windows',
                    'wix'=>'Wix',
                    'wordpress'=>'Wordpress',
                    'yahoo'=>'Yahoo',
                    'yelp'=>'Yelp',
                    'youtube'=>'Youtube',
                    'zoom'=>'Zoom',
                
            ]
        ],
        'navbar' => [
            'swblog'=>['swpost', 'type/swpost']
         ],
        'resource' =>[
            'swpost' => [
                'groups' => ['admin', 'editor', 'super'],
                'key' => 'SWP',
            ],
            'swblog' => [
                'groups' => ['admin', 'editor', 'super'],
                'key' => 'SWB',
            ],
        ],
    ],
	'jsonadm' => [

	],
];
    
